# CodeQL does not support Rust yet, so we're using Clippy instead.

name: Analyse

on:
  push:
    paths:
      - '**'
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    paths:
      - '**'
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup component add clippy

      - name: Install dependencies
        run: cargo install clippy-sarif sarif-fmt

      - name: Analyse code
        continue-on-error: true
        run: cargo clippy --all-features --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
